version: "3"
services:
    db:
        image: mysql:latest
        expose:
            - "3306"
        ports:
            - "3307:3306"
        env_file:
            - ./.env.development
        volumes:
            - db_data:/var/lib/mysql
        container_name: shopify-clone-db
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        expose:
            - "6379"
        restart: "on-failure"
        volumes:
            - redis_data:/var/lib/redos
        container_name: shopify-clone-redis
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./
        volumes:
            - ./nodemon.json:/usr/app/nodemon.json
            - ./:/usr/app/
            - /usr/app/node_modules
            - /usr/app/dist
            - /usr/app/coverage
        env_file:
            - ./.env.development
        environment:
            - NODE_ENV=development
        depends_on:
            - db
            - redis
        expose:
            - "3000"
        ports:
            - "3000:3000"
            - "9229:9229"
        container_name: shopify-clone-api
        entrypoint: ./entrypoint.sh
        command: /usr/app/entrypoint.sh
volumes:
    db_data: {}
    redis_data: {}
