version: '3'
services: 
    db:
        image:  mysql:latest
        expose: 
            - "3306"
        ports:
            - "3307:3306"
        env_file: 
            - ./src/.env.development
        volumes: 
            - db_data:/var/lib/mysql
        container_name: shopify-clone-db
    api:
        build: 
            dockerfile: Dockerfile.dev
            context: ./
        volumes: 
            - ./nodemon.json:/usr/app/nodemon.json
            - ./:/usr/app/
            - /usr/app/node_modules
            - /usr/app/dist 
            - /usr/app/coverage
        env_file: 
            - ./src/.env.development
        environment:
            - NODE_ENV=development
        depends_on: 
            - db
        expose: 
            - "3000"
        ports: 
            - "3000:3000"
            - "9229:9229"
        links: 
            - db
        container_name: shopify-clone-api
volumes: 
    db_data: {}