name: Analyze pull request2

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - master
      - main
      - sonar-github-actions
      - development

jobs:
  unit-test-code:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.15.4
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.4"
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Run Tests
        run: npm run ci-test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-info
          path: ./coverage/lcov.info
  sonar-qube-pr-analysis:
    needs: unit-test-code
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report-info
          path: ./reports/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./reports/
      # - name: RUN SONARQUBE PR
      #   run: |
      #     docker run \
      #     --rm \
      #     -e SONAR_HOST_URL=${{ secrets.SONAR_PROJECT_PR_URL }}  \
      #     -e SONAR_LOGIN=${{ secrets.SONAR_PROJECT_PR_TOKEN }} \
      #     -v "$PWD:/usr/src" \
      #     sonarsource/sonar-scanner-cli \
      #     -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
      #     -Dsonar.pullrequest.key=${{ github.event.number }} \
      #     -Dsonar.pullrequest.branch=${{ github.HEAD_REF }} \
      #     -Dsonar.pullrequest.base=development \
      #     -Dsonar.pullrequest.github.repository=${{ github.repository }} \
      #     -Dsonar.qualitygate.wait=true \
      #     -Dsonar.scm.provider=git
